
GET http://localhost:3000/events

###
# @name createEvent
POST http://localhost:3000/events
Content-Type: application/json

{
    "name": "New Event",
    "description": "This is a new event",
    "price": 100,
    "date": "2017-01-01T00:00:00"
}

### 
@eventId = {{ createEvent.response.body.id }}

###
GET http://localhost:3000/events/{{eventId}}


###
PATCH  http://localhost:3000/events/{{eventId}}
Content-Type: application/json

{
    "name": "New Event Updated",
    "description": "This is a new event updated",
    "price": 110,
    "date": "2017-02-01T00:00:00"
}


###
DELETE http://localhost:3000/events/{{eventId}}



### 

GET http://localhost:3000/events/76976026-475e-456c-a4c3-e0d558da3497/spots

###

POST http://localhost:3000/events/76976026-475e-456c-a4c3-e0d558da3497/spots
Content-Type: application/json

{
    "name": "A1"
}

###
GET http://localhost:3000/events/76976026-475e-456c-a4c3-e0d558da3497/spots/c6f9d0c1-fc83-4552-8d25-5a3050ca9855


###
PATCH  http://localhost:3000/events/76976026-475e-456c-a4c3-e0d558da3497/spots/c6f9d0c1-fc83-4552-8d25-5a3050ca9855
Content-Type: application/json

{
    "name": "A2"
}


###
DELETE http://localhost:3000/events/76976026-475e-456c-a4c3-e0d558da3497/spots/c6f9d0c1-fc83-4552-8d25-5a3050ca9855